### PR TITLE
Import R.utils to fread() a compressed file

### PR DESCRIPTION
**Pull request by jdblischak**
In order to use `data.table::fread()` on a compressed file, the dependency R.utils has to be installed.

This feature was introduced in data.table version [1.11.8](https://github.com/Rdatatable/data.table/blob/master/NEWS.md#datatable-v1118--30-sep-2018). The original poster in Issue #2 received an error because they were using 1.11.4.

However, data.table only lists R.utils as a [suggested dependency](https://github.com/Rdatatable/data.table/blob/50f815780297aaea5e30e9fe3c787d931957fe21/DESCRIPTION#L48), and it has [error handling code](https://github.com/Rdatatable/data.table/blob/50f815780297aaea5e30e9fe3c787d931957fe21/R/fread.R#L107) to alert the user if they try to `fread()` a compressed file without R.utils installed.

Since packageRank always needs this feature to read the compressed cran logs file, this PR adds R.utils to the list of imported dependencies.

Here's a demonstration:

```
> packageVersion("packageRank")
[1] ‘0.3.0’
> library(packageRank)
> packageRank("packageRank", memoization = FALSE)
trying URL 'http://cran-logs.rstudio.com/2019/2019-10-27.csv.gz'
Content type 'application/gzip' length 27973872 bytes (26.7 MB)
==================================================
downloaded 26.7 MB

Error in data.table::fread(x) : 
  To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'.
> install.packages("R.utils")
> packageRank("packageRank", memoization = FALSE)
trying URL 'http://cran-logs.rstudio.com/2019/2019-10-27.csv.gz'
Content type 'application/gzip' length 27973872 bytes (26.7 MB)
==================================================
downloaded 26.7 MB

        date    packages downloads percentile            rank
1 2019-10-27 packageRank        12       78.6 3,205 of 15,297
```

### CODE REVIEW

**Comment by lindbrook** [comment]
Thanks for looking at this! It's been bugging me.

Isn't this supposed to be "solved" by specifying a minimum version in DESCRIPTION? For example, I use:

Imports: data.table (>= 1.12.2)

I don't have 'R.utils' on my machine and I don't get the error you got. 

Perhaps item 4 in [v1.12.0](https://github.com/Rdatatable/data.table/blob/master/NEWS.md#datatable-v1120--13-jan-2019), which is a bit cryptic to me, changed something. 

That said, I see the line you highlighted in the source code. Let me try to replicate what you got. My preference is to minimize package dependencies if at all possible.

**Comment by jdblischak** [comment]
> Thanks for looking at this! It's been bugging me.

No problem. Thanks for creating such a useful package!

> Isn't this supposed to be "solved" by specifying a minimum version in DESCRIPTION?

That only solves the issue of an outdated version of data.table. Because R.utils is a suggested package, it still isn't installed with a vanilla `install.packages("packageRank")`.

> I don't have 'R.utils' on my machine and I don't get the error you got.

That is surprising. Would it be possible for you to recreate this situation so I can test it? e.g. using Docker, RStudio Cloud, etc.

For example, you can recreate my example above using the Docker image rocker/tidyverse:

```
docker run -it --rm rocker/tidyverse@sha256:b8ae9950d93aafa5e553493613de8ce04916a57565818a9cd544907f83893d76 R
```

And running the following:

```
install.package("packageRank")
packageRank::packageRank("packageRank", date = Sys.Date() - 7, memoization = FALSE)
install.packages("R.utils")
packageRank::packageRank("packageRank", date = Sys.Date() - 7, memoization = FALSE)
```

> Perhaps item 4 in v1.12.0, which is a bit cryptic to me, changed something.

Ah, yes. Good point. I had missed that detail. Your package needs this feature since you pass a URL to `data.table::fread()`. Basically, data.table 1.11.8 added the ability to read a compressed file from disk, and data.table 1.12.0 added the ability to read a compressed file from a remote URL.

> My preference is to minimize package dependencies if at all possible.

I 100% agree with that preference. I think it makes sense for data.table to only suggest R.utils since a user can use data.table without needing to import a compressed file. On the other hand, since the namesake function `packageRank::packageRank()` needs to import a compressed file, I think it makes sense to import R.utils.

**Comment by jdblischak** [comment]
I updated the PR to explicitly load the required function `decompressFile` from the R.utils package. This avoids the following NOTE from `R CMD check`:

```
* checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘R.utils’
  All declared Imports should be used.
```

**Comment by lindbrook** [comment]
I did a clean install of R. I deleted the R application and the frameworks (R libraries). I then installed 'packageRank' from CRAN. The following dependencies were installed: 

c('sys', 'backports', 'ellipsis', 'zeallot', 'askpass', 'glue', 'magrittr', 'stringi', 'colorspace', 'assertthat', 'utf8', 'vctrs', 'mime', 'openssl', 'R6', 'plyr', 'Rcpp', 'stringr', 'labeling', 'munsell', 'RColorBrewer', 'cli', 'crayon', 'fansi', 'pillar', 'pkgconfig', 'httr', 'jsonlite', 'digest', 'gtable', 'lazyeval', 'reshape2', 'rlang', 'scales', 'tibble', 'viridisLite', 'withr', 'bitops', 'curl', 'xml2', 'cranlogs', 'data.table', 'ggplot2', 'memoise', 'RCurl', 'rversions')

I was then able to replicate the error message about 'R.utils'. I installed 'R.utils'. The following dependencies were installed: c('R.oo', 'R.methodsS3'). I'm not sure why 'packageRank' worked without it before.

**Comment by lindbrook** [comment]
Thanks!

**Comment by lindbrook** [comment]
Have you opened a pull request or issue about this at 'data.table'?

**Comment by jdblischak** [comment]
> Have you opened a pull request or issue about this at 'data.table'?

Could you please provide more explanation? I am not aware of any issue with the data.table package.

**Comment by lindbrook** [comment]
That 'data.table' should move 'R.utils' from Suggests to Imports in its DESCRIPTION file for use with data.table::fread()

**Comment by jdblischak** [comment]
> That 'data.table' should move 'R.utils' from Suggests to Imports in its DESCRIPTION file for use with data.table::fread()

I would advise against making that suggestion to the data.table authors. They follow the conventions outlined in [Suggested Packages from Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages) and [Dependencies from R Packages](http://r-pkgs.had.co.nz/description.html#dependencies).

For the data.table package, R.utils is only needed in a very narrow scope, i.e. to import compressed data files. Since data.table can be used without reading compressed data files, the authors have decided to list it in Suggests. Since packageRank requires the ability to read compressed data files, it makes sense for packageRank to list R.utils in Imports.

I recently had a similar situation with my workflowr package. It uses the httr package for OAuth authentication with the GitHub API. To perform OAuth authentication, httr requires the package httpuv. However, httpuv is only a suggested package for httr because httpuv is only needed for OAuth authentication. Since workflowr requires the OAuth feature, I added httpuv to the Imports for workflowr. This way httpuv is always installed when workflowr is installed.

**Comment by lindbrook** [comment]
Thanks for the info.

**Pull request merged**
